### ISSUE TITLE
VNTRTyper ArrayIndexOutOfBoundsException when handling BAM records with >65535 CIGAR operations

### ISSUE THREAD

**Issue by c-zhou** [mdcao/japsa#27]
When handling BAM records with >65535 CIGAR operations, VNTRTyper will throw an ArrayIndexOutOfBoundsException.

Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 516984
	at japsa.tools.bio.hts.VNTRLongReadsCmd.getReadPosition(VNTRLongReadsCmd.java:770)
	at japsa.tools.bio.hts.VNTRLongReadsCmd.main(VNTRLongReadsCmd.java:288)

**Comment by hsnguyen** [comment]
Update to htsjdk 2.18.2 as suggested in commit https://github.com/mdcao/japsa/commit/d83e942545c3cb22f2342141145a80855f4dc410

**Comment by mdcao** [comment]
this is an issue with old version of libsdk
